pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
       stage('Prepare Environment') { 
        steps { cleanWs() 
              echo "Workspace cleaned successfully." } }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
